### ISSUE TITLE
Skew-symmetric matrices as generators for rotations

### ISSUE THREAD

**Issue by andyferris** [JuliaGeometry/Rotations.jl#30] opened 2017-04-20 12:21 UTC
See #29.

I think it would be great to have a skew-symmetric matrix type that can be exponentiated into a `Rotation`, and vice-versa via `log`. These would form a Lie algebra to complement the Lie group of rotations.

Similarly to the rotations, these could have simplified parameterizations that are similar to `AngleAxis` and `RodriguesVec`.

**Comment by bzinberg** [comment] 2020-07-22 13:50
It would be great to have the type of "Lie algebra element" be distinct from "Lie group element."  Currently, `log` of a `UnitQuaternion` returns an "un-normalized unit quaternion," but there's no spec of what that means other than "for efficiency reasons we don't check unit length, so the caller should check that themself."  Log of a unit quaternion does not belong in that type, because it is actually correct and necessary to allow non-unit length.

I think the conflating of Lie group elements with Lie algebra elements is the root cause of https://github.com/JuliaGeometry/Rotations.jl/issues/126.

Also, there should be some type for which `Base.zero` returns the zero element of the Lie algebra.

**Comment by tkoolen** [comment] 2020-07-24 03:08
One option could be to use `RotationVec` as the Lie algebra element, since it can be identified with the skew-symmetric matrix. That's kind of the approach I took with twists in RigidBodyDynamics.jl.

**Comment by bzinberg** [comment] 2020-07-24 17:18
To fix https://github.com/JuliaGeometry/Rotations.jl/issues/128, I think we may also need a distinct representation for the Lie algebra of unit quaternions.  Related to that, I have some use cases [1] that rely on distinguishing between the quaternions `q` and `-q`.  Maybe this package wants to specifically disclaim responsibility for maintaining that distinction; AFAICS it doesn't take a clear stance: `q == -q` but then we support exponential where that difference matters.

[1] I'm working with generative models of continuously changing quaternions, so I think I need to rely on `UnitQuaternion`s remembering their components (i.e. not switching from `q` to `-q`, as long as the user doesn't round-trip convert them between other formats of course).  Also, in SLERP interpolation, switching one of the endpoints from `q` to `-q` changes the path (I think this corresponds to traveling along a geodesic the short way vs. the long way, but not sure).

**Comment by andyferris** [comment] 2020-07-24 23:02
I'd be tempted to build a family of representations of real 3x3 skew-symmetric matrices, starting with the obvious matrix-like one, but then also generators for `RotationVec` and `Quaternion` and so on. We can define `exp` and `log` to map between the group and algebra elements.

For unit quaternions our *representation* has an aditional `Z(2)` "gauge" (is it basically isomorphic to SU(2) x Z(2)?) I could possibly imagine an additional group element which is basically an identity matrix but maps `q` to "`-q`" under multiplication (the quotes are because `-` is actually defined in terms of 3x3 matrices here...).  I suppose there's an actual quaternion for that but I'm not sure if an explicit singleton or 1-bit `struct` would be good so each quaternion can be represented exactly as `exp(quaternion_generator) * quaternion_guage`. Would that be useful to anyone?

(We can't put that bit inside the quaternion generator because then addition becomes ambiguous).

**Comment by bzinberg** [comment] 2020-07-25 03:37
Representing skew-symmetric matrices by their three free entries sounds
great.  For quaternions though, representation of the unit quaternion Lie
algebra is even more straightforward than the so(3) Lie algebra: a tangent
vector at the identity quaternion can be written as a pure-imaginary
infinitesimal (a * ∂/∂x + b * ∂/∂y + c * ∂/∂z), and I think it is best to
use this natural identification of the unit quaternion Lie algebra with
R^3, rather than trying to build some other bijection (especially if it's
discontinuous).

Regarding the Lie groups, (if I understand the notation correctly) the unit
quaternions are not isomorphic to SO(3) × (Z/2Z).  The map from unit
quaternions to SO(3) is a connected two-sheeted cover, so (very)
schematically speaking it looks like this
<https://en.wikipedia.org/wiki/Riemann_surface#/media/File:Riemann_sqrt.svg>
rather than like this
<https://en.wikipedia.org/wiki/Covering_space#/media/File:Covering_space_diagram.svg>.
Any particular choice of how to locally decompose into a direct product
would have singularities when one attempts to extend it to a global
definition, thus losing the advantages quaternions have over other
representations.  So I think it's best to stick with representing unit
quaternions directly as `(w, x, y, z)`.

> (We can't put that bit inside the quaternion generator because then
addition becomes ambiguous).

More ambiguous than it already is?  The log function is already
multi-valued.  Actually I'm now realizing that even in the original
formalism, a definition like q^t = exp(t * log(q)) depends on the branch
cut when t isn't an integer, and I'm wondering what that means for the
behavior of SLERP interpolation...

**Comment by hyrodium** [comment] 2021-11-06 06:01
>A unit-magnitude complex (respectively quaternion) number has a representation as 2-by-2 (respectively 3-by-3) real orthogonal matrix.

It seems the example is not correct here, because `Complex <: AbstractMatrix` is `false`.
In this package, a 3D rotation is treated as a 3×3 matrix.

>Personally, I am in favor of a breaking release of this package that removes the behavior that conflates elements of the rotation group with their linear representation. Not to mention the double-cover issue.

I think that will break the main concept of the package. Making a new package with a different name will be better, I guess.
Some of the problems will be fixed with #190.

**Comment by goretkin** [comment] 2021-11-06 06:33
> It seems the example is not correct here, because Complex <: AbstractMatrix is false.

That's exactly what I mean. A unit-complex/unit-quaternion is an efficient parameterization for a rotation in 2D/3D. 

btw, this did introduce 2D `Rotations` type that `<:AbstractMatrix`, but parameterized by an angle, not a unit complex number.
https://github.com/JuliaGeometry/Rotations.jl/pull/89

> I think that will break the main concept of the package. Making a new package with a different name will be better, I guess.

It is a big part of `Rotations.jl`, true. I also value that the package provides many different methods for constructing rotations , and also types like `RotX` that encode information into the type system for the sake of multiple dispatch (in some cases? I have not checked recently.)

**Closed** 2022-01-13 10:33 UTC
Labels: Lie algebra
